name: Edit Role
description: Edit a Job Posting on our list
title: "Editing Role"
labels: ["edit_role"]
body:
  - type: markdown
    attributes:
      value: |
        ## Edit Job Posting Form
        Thanks for taking the time to contribute!
        Make sure you've read `CONTRIBUTING.md` before submitting your edits
        Please only fill in **link, reason, and whichever fields you would like to edit**
        You may leave the others empty
  - type: input
    id: url
    attributes:
      label: Link to Job Posting
      placeholder: ex. example.com/link/to/posting
    validations:
      required: true
  - type: input
    id: company_name
    attributes:
      label: Company Name
      placeholder: ex. Google
    validations:
      required: false
  - type: input
    id: title
    attributes:
      label: Job Title
      placeholder: ex. ML Software Engineer
    validations:
      required: false
  - type: input
    id: location
    attributes:
      label: Location
      description: |
        Where is the job located?
        Please separate locations with a pipe "|" if there are multiple options. 
        Include Remote if remote option available.
      placeholder: ex. San Franciso, CA | Austin, TX | Remote
    validations:
      required: false
  - type: dropdown
    id: sponsorship
    attributes:
      label: Does this job offer sponsorship?
      description: |
        If the posting does not fall into one of these
        categories, select "Other" then specify in parentheses at the end of
        the Job Title what the sponsorship status is
      multiple: false
      options:
        - Offers Sponsorship
        - Does Not Offer Sponsorship
        - U.S. Citizenship is Required
        - Other
    validations:
      required: false
  - type: dropdown
    id: active
    attributes:
      label: Is this job posting currently accepting applications?
      multiple: false
      options:
        - "Yes"
        - "No"
    validations:
      required: false
  - type: checkboxes
    id: is_visible
    attributes:
      label: Remove this job from the list?
      description: Only check this box if this job is fake, does not fit the theme of the repo, or is offensive.
      options:
        - label: "Yes, remove this job"
  - type: input
    id: email
    attributes:
      label: Email associated with your GitHub account (Optional)
      description: |
        If you would like to be listed as the contributor to the repository when our github action 
        commits your contribution to the repo, please provide your email. This is the only time your 
        email will be used. If left blank, your contribution will still be made, but it will be made 
        by the bot actions@github.com.
      placeholder: ex. firstLast@gmail.com
    validations:
      required: false
  - type: textarea
    id: reason
    attributes:
      label: Reason for edit
      description: If the reason for your edit is not obvious, please explain here.
      placeholder: This job is no longer accepting applications...
    validations:
      required: false
      
